name: Release to dev
on:
  push:
    branches:
      - main

env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}

jobs:
  build-and-deploy:
    uses: Cerebellum-Network/reusable-workflows/.github/workflows/build-and-upload-static.yaml@master
    with:
      runs-on: '["self-hosted", "cere-network-large-workers"]'
      build_container: 'node:18.16.0-slim'
      deploy_container: 'ubuntu:20.04'
      install_packages_command: 'yarn'
      build_command: 'yarn build'
      path_to_static_files_to_upload: 'build'
    secrets:
      NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      NETWORK_AWS_ACCESS_KEY_ID: ${{ secrets.DEV_NETWORK_AWS_ACCESS_KEY_ID }}
      NETWORK_AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_NETWORK_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME_DEV }}
      CF_DISTRIBUTION_ID: ${{ secrets.CF_DISTRIBUTION_ID_DEV }}
